repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: clippy

-   repo: local
    hooks:
      - id: generate_tree
        name: generate tree
        entry: >
          bash -c "tree-generator -o ./docs/auto/project_structure.txt"
        language: system

      - id: file_merger
        name: merge files
        entry: >
          bash -c "file-merger -d ./crates/cs-protocol -r -o ./docs/auto/all_cs-protocol.txt &&
          file-merger -d ./crates/cs-server -r -o ./docs/auto/all_cs-server.txt &&
          file-merger -d ./ -r -p "Cargo.toml" -o ./docs/auto/all_Cargo-toml.txt"
        language: system
