[workspace]
members = [
    "crates/cs-protocol",
    "crates/cs-server",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.48", features = ["full"] }                # для асинхронной работы (сети, таймеры).
serde = { version = "1.0.228", features = ["derive"] }           # для превращения наших Rust-структур в JSON и обратно.
serde_json = "1.0.145"                                           # для превращения наших Rust-структур в JSON и обратно.
tracing = "0.1.43"                                               # для красивого и полезного логирования.
tracing-subscriber = "0.3.22"                                    # Для вывода логов в консоль
axum = "0.8.7"                                                   # Веб-фреймворк
